apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-desk
  namespace: {{ .Values.namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # TODO(human): ingressClassName depuis values.yaml (nginx en local, alb sur EKS en Phase 5).
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: support-desk
                port:
                  number: 80
