apiVersion: v1
kind: Secret
metadata:
  name: support-desk-secret
type: Opaque
stringData:
  DB_USER: "support_desk"
  DB_PASSWORD: "support_desk_password"
  MYSQL_ROOT_PASSWORD: "local_root_password"
