apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-desk
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: support-desk
  template:
    metadata:
      labels:
        app: support-desk
    spec:
      containers:
        - name: support-desk
          image: support-desk:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
