apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: support-desk
  namespace: support-desk
spec:
  # TODO(human): quelle ingressClassName ? Indice : `kubectl get ingressclass` liste celle(s)
  # créée(s) par le controller qu'on vient d'installer.
  ingressClassName: nginx
  rules:
    - http: # pas de "host:" ici, volontairement (voir explication ci-dessus)
        paths:
          - path: /
            # TODO(human): Prefix ou Exact pour matcher toute l'app depuis la racine ?
            pathType: Prefix
            backend:
              service:
                # TODO(human): quel Service cible, et sur quel port ? Indice : regarde service.yaml.
                name: support-desk
                port:
                  number: 80
