apiVersion: v2
name: support-desk
description: Highly available support desk app (Flask + MySQL), deployable on kind or EKS
type: application
version: 0.1.0       # version du chart lui-même (incrémente à chaque changement de template/structure)
appVersion: "1.0.2"  # version de l'application packagée (le tag d'image par défaut)
